services:
  postgres:
    image: postgres:16
    container_name: ${APP_NAME:-gohst}-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - gohst-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/data:/docker-entrypoint-initdb.d
    networks:
      - gohst-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${APP_NAME:-gohst}-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    ports:
      - "5050:80"
    networks:
      - gohst-network
    depends_on:
      - gohst-postgres
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
networks:
  gohst-network:
    driver: bridge

volumes:
  gohst-postgres-data:
    external: false
